### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by ger630** [mortonfox/shoprite-load-all-to-card#1]
Shoprite must have changed something as the button no longer appears.  Thanks!

**Comment by mortonfox** [comment]
Have you updated the extension yet?

I noticed the problem and made a change to it 8 days ago: https://github.com/mortonfox/shoprite-load-all-to-card/commit/8a4a018891f994a976b97aacef70131811b36e6c

It wasn't a simple fix this time. ShopRite's webdev modified something else under the hood that broke the straightforward iteration over the list of buttons. However, "clicking" on the buttons in reverse order still works for now.

**Comment by ger630** [comment]
Thanks for the reply!

Updated, on one, redownloaded on another, still no load all is showing.
Don't know what you mean by reverse order....is that the method you used in the script?

Thanks again.

**Comment by mortonfox** [comment]
I had to move the button to a different spot due to the site redesign. Is it not showing up in the corner above “Digital Coupon Center”?

<img width="518" alt="Screenshot of Microsoft Edge (7-17-19, 1-23-02 PM)" src="https://user-images.githubusercontent.com/495892/61396585-08572380-a896-11e9-981f-458936c15fdf.png">

**Comment by whaddausay** [comment]
Wondering if anyone can help me I keep getting


 Failed to load extension
File
~\Downloads\shoprite-load-all-to-card-master
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by mortonfox** [comment]
@whaddausay Is it possible that you need to use forward slashes instead of backslashes in the path?

**Comment by whaddausay** [comment]
I still cant get this to work

**Comment by ger630** [comment]
FYI you can close this issue now.  Thank you.
