### ISSUE TITLE
New ShopRite New Broken

### ISSUE THREAD

**Issue by bestmarty** [mortonfox/shoprite-load-all-to-card#2]
With the New Shoprite update the button no longer appears on the coupon page

**Comment by f1rstxlas7** [comment]
Looks like the element's class name has changed from 'available-to-clip' to 'available-to-clip ng-star-inserted' and the domain for the script will have to be changed to www.shoprite.com too. On top of the button problem, that is.

**Comment by ionizer5** [comment]
Any chances we can get this fixed?

**Comment by ionizer5** [comment]
> Looks like the element's class name has changed from 'available-to-clip' to 'available-to-clip ng-star-inserted' and the domain for the script will have to be changed to [www.shoprite.com](http://www.shoprite.com) too. On top of the button problem, that is.

Do you know how to fix it and fork from this?  Not sure if original owner is fixing it or not?

**Comment by bestmarty** [comment]
Last commit fixed the issue in the Manifest
